name: overview
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  github: ^9.24.0
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0
  get_it: ^8.0.2
  dartz: 0.10.1
  extended_image: ^9.0.7
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.0

  styleguide:
    path: styleguide

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
