name: overview
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  github: ^9.2.0
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  extended_image: ^6.0.3
  shared_preferences: ^2.0.13
  fl_chart: ^0.50.1

  styleguide:
    path: styleguide

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  build_runner: ^2.1.10
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
