name: overview
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  github: ^9.11.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  get_it: ^7.2.0
  dartz: ^0.10.1
  extended_image: ^7.0.2
  shared_preferences: ^2.1.0
  fl_chart: ^0.61.0

  styleguide:
    path: styleguide

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  mockito: ^5.4.0
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
