name: overview
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  github: 9.19.0
  flutter_bloc: 8.1.3
  injectable: 2.3.0
  get_it: 7.6.4
  dartz: 0.10.1
  extended_image: 8.1.1
  shared_preferences: 2.2.1
  fl_chart: 0.63.0

  styleguide:
    path: styleguide

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
  build_runner: 2.4.6
  injectable_generator: 2.4.0
  mockito: 5.4.2
  bloc_test: 9.1.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
